In [1]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt
%matplotlib inline
import pickle
from flask import Flask, abort, jsonify, request
import json
import requests

In [2]:
with open("model_k1.pkl", 'rb') as file:  
    model = pickle.load(file)

In [3]:
model

KMeans(algorithm='auto', copy_x=True, init='k-means++', max_iter=300,
    n_clusters=5, n_init=10, n_jobs=None, precompute_distances='auto',
    random_state=0, tol=0.0001, verbose=0)

In [30]:
exemple =pd.DataFrame([[40,2]],columns=['Annual Income (k$)',
       'Spending Score (1-100)'])
exemple

Annual Income (k$)  Spending Score (1-100)
0                  40                       2

In [31]:
model.predict(exemple)

array([4], dtype=int32)

In [32]:
ex=[[1,2],[44,100],[30,2],[60,20]]

In [33]:
model.predict(ex)

array([4, 3, 4, 0], dtype=int32)

In [34]:
ex2=[[30,2]]

In [35]:
print(model.predict(ex2))

[4]


In [36]:
print(model.predict(ex))

[4 3 4 0]


In [4]:
url = "http://localhost:9000/api"
data = json.dumps({'ai':40, 'sc': 26})
r = requests.post(url, data)
try:
    print(r.json())
except json.decoder.JSONDecodeError:
    print("N'est pas JSON")

{'results': 4}


In [21]:
rez = model.predict(ex2)


In [22]:
rez[0]

4

<Response [500]>